server:
  port: 8080

spring:
  application:
    name: 'lixt'
    
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: lixt
    url: jdbc:mysql://localhost/lixt?useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        default_schema: lixt

  flyway:
    baseline-on-migrate: true
    schemas: lixt

lixt:
  mail:
    username: 
    password: 

