spring:
  datasource:
    driverClassName:
    url: jdbc:mysql://localhost/lixt?useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 123456

lixt:
  base:
    url: http://localhost:8080
  mail:
    server: localhost
    port: 1025
    username: test@mailhog.example
    password: senha