server:
  port: 8080

spring:
  application:
    name: 'lixt'
    
  profiles:
    active: @activatedProperties@
    
  datasource:
    hikari:
      schema: lixt

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        default_schema: lixt

  flyway:
    baseline-on-migrate: true
    schemas: lixt

lixt:
  mail:
    username: noreply.lixt@gmail.com
    password: lixtapp2021!

