spring:
  datasource:
    driverClassName: software.aws.rds.jdbc.Driver
    url: jdbc:mysql:aws://lixt-db-cluster.cluster-cpqytoinpxge.us-east-1.rds.amazonaws.com:3306
    username: root
    password: dMh71CPycRIjKk0tJ8DQ
