spring:
  datasource:
    driverClassName:
    url: jdbc:mysql://localhost/lixt?useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 123456

lixt:
  base:
    url: http://localhost:8080
  mail:
    server: smtp.gmail.com
    port: 465
    username: noreply.lixt@gmail.com
    password: xpdypabuvxlpkueb

  barcode:
    url: https://api.cosmos.bluesoft.com.br/gtins/
    token: KlrbMerss0GnOBwvj2g9-g
    api: https://cosmos.bluesoft.com.br/api

  geolocation:
    url: https://api.mapbox.com/geocoding/v5/mapbox.places/
    token: pk.eyJ1IjoibGl4dCIsImEiOiJja3Vsamw3azUxbWlyMnhteGsxZWZ5dzJtIn0.x6k9-84Te7yYg6EETauq4w