server:
  port: 8080

spring:
  application:
    name: 'lixt'

  profiles:
    active: @activatedProperties@

  datasource:
    hikari:
      schema: lixt

  jpa:
    hibernate.ddl-auto: update
    show-sql: false

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        default_schema: lixt

  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: lixt

lixt:
  version: @project.version@

  basic:
    auth:
      clientId: client
      secretId: 123456

  mail:
    username: noreply.lixt@gmail.com
    password: lixtapp2021!!

  barcode:
    url: https://api.cosmos.bluesoft.com.br/gtins/
    token: KlrbMerss0GnOBwvj2g9-g
    api: https://cosmos.bluesoft.com.br/api

