server:
  port: 8080

spring:
  application:
    name: 'lixt'
    
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: lixt
    url: jdbc:mysql://localhost/lixt?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_schema: lixt

  flyway:
    baseline-on-migrate: true
    schemas: lixt

lixt:
  mail:
    username: 
    password: 

