spring:
  datasource:
    driverClassName:
    url: jdbc:mysql://lixt-db.mysql.database.azure.com:3306/lixt_db?useSSL=true&requireSSL=false
    username: lixt_root@lixt-db
    password: SenhadaAzure123!
