server:
  port: 8080

spring:
  application:
    name: 'lixt'
    
  profiles:
    active: @activatedProperties@
    
  datasource:
    hikari:
      schema: lixt

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        default_schema: lixt

  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: lixt

lixt:
  version: @project.version@
  
  basic:
    auth:
      clientId: client
      secretId: 123456
    
  barcode:
    url: https://api.cosmos.bluesoft.com.br/gtins/
    token: ${INTEGRATION_BARCODE_TOKEN}
    api: https://cosmos.bluesoft.com.br/api

  geolocation:
    url: https://api.mapbox.com/geocoding/v5/mapbox.places/
    token: ${INTEGRATION_GEOLOCATION_TOKEN}

  jwt:
    secretKey: ${JWT_SECRET_KEY}
    tokenExpirationAfterMillis: 86400000

  mail:
    server: smtp.gmail.com
    port: 465
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}

