spring:
  datasource:
    driverClassName:
    url: ${DATABASE_STRING_CONNECTION}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

lixt:
  base:
    url: https://lixt-ws.azurewebsites.net/
    